# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simexOutcome <- function(pred_mat, lambdavec, fail_times, fail_ind, init_b, B, simex_sd, n) {
    .Call(`_SimexSurvOutcome_simexOutcome`, pred_mat, lambdavec, fail_times, fail_ind, init_b, B, simex_sd, n)
}

fastLM <- function(X, y) {
    .Call(`_SimexSurvOutcome_fastLM`, X, y)
}

newtonRaphson <- function(pred_mat, curr_beta, failure_mat) {
    .Call(`_SimexSurvOutcome_newtonRaphson`, pred_mat, curr_beta, failure_mat)
}

quadExtrapolation <- function(lambda_mat, coef1_mat, coef2_mat, coef3_mat) {
    .Call(`_SimexSurvOutcome_quadExtrapolation`, lambda_mat, coef1_mat, coef2_mat, coef3_mat)
}

